# Generated by Django 4.2 on 2023-05-22 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='interesting',
            field=models.CharField(choices=[('Art', 'choices_1'), ('Busines', 'choices_2'), ('Danger', 'choices_3'), ('Internet', 'choices_4'), ('Songs', 'choices_5'), ('Artist', 'choices_6'), ('Sport', 'choices_8'), ('River', 'choices_9'), ('Travel', 'choices_10')], default='persional'),
        ),
    ]
