# Generated by Django 4.2 on 2023-05-23 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_interesting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='interesting',
            field=models.CharField(choices=[('choices_1', 'Art'), ('choices_2', 'Busines'), ('choices_3', 'Danger'), ('choices_4', 'Internet'), ('coices_5', 'Songs'), ('choices_6', 'Artist'), ('choices_8', 'Sport'), ('choices_9', 'River'), ('choices_10', 'Travel')], default='persional'),
        ),
    ]
