# Generated by Django 4.2 on 2023-05-23 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_interesting',
            field=models.CharField(choices=[('choices_1', 'Art'), ('choices_2', 'Busines'), ('choices_3', 'Danger'), ('choices_4', 'Internet'), ('coices_5', 'Songs'), ('choices_6', 'Artist'), ('choices_8', 'Sport'), ('choices_9', 'River'), ('choices_10', 'Travel')], default=[('choices_11', 'persional')]),
        ),
    ]
