# Generated by Django 4.2 on 2023-05-24 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_comment_parent_alter_comment_blog_alter_comment_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_interesting',
            field=models.CharField(choices=[('art', 'Art'), ('busines', 'Busines'), ('danger', 'Danger'), ('internet', 'Internet'), ('songs', 'Songs'), ('artist', 'Artist'), ('sport', 'Sport'), ('river', 'River'), ('travel', 'Travel')], default=[('persional', 'Persional')]),
        ),
    ]
